// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllHistory() {
  return window['go']['main']['App']['DeleteAllHistory']();
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function MoveRequest(arg1) {
  return window['go']['main']['App']['MoveRequest'](arg1);
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}
