// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {types} from '../models';

export function CheckForUpdates():Promise<services.VersionInfo>;

export function DeleteAllHistory():Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function LoadCollections():Promise<Array<types.Collection>>;

export function LoadHistory():Promise<Array<types.HistoryItem>>;

export function MoveRequest(arg1:types.MoveRequestPayload):Promise<void>;

export function SaveCollections(arg1:Array<types.Collection>):Promise<void>;

export function SaveHistory(arg1:Array<types.HistoryItem>):Promise<void>;

export function SendRequest(arg1:types.RequestData):Promise<types.ResponseData>;
